# Generated by Django 5.2.4 on 2025-08-09 14:24

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='trial', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField()),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('api_calls_used', models.PositiveIntegerField(default=0)),
                ('storage_used_gb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subscription_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'organization_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('numeric_value', models.PositiveIntegerField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'plan_features',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount'), ('free_trial', 'Extended Free Trial')], max_length=20)),
                ('percentage_off', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amount_off', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('free_trial_days', models.PositiveIntegerField(blank=True, null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, null=True)),
                ('current_redemptions', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_time_customers_only', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'subscription_discounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('created', 'Subscription Created'), ('activated', 'Subscription Activated'), ('plan_changed', 'Plan Changed'), ('cancelled', 'Subscription Cancelled'), ('renewed', 'Subscription Renewed'), ('expired', 'Subscription Expired'), ('trial_started', 'Trial Started'), ('trial_ended', 'Trial Ended'), ('payment_succeeded', 'Payment Succeeded'), ('payment_failed', 'Payment Failed'), ('usage_limit_exceeded', 'Usage Limit Exceeded'), ('suspended', 'Subscription Suspended'), ('reactivated', 'Subscription Reactivated')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'subscription_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('feature_key', models.CharField(max_length=50, unique=True)),
                ('feature_type', models.CharField(choices=[('boolean', 'Boolean (Yes/No)'), ('numeric', 'Numeric Limit'), ('text', 'Text Value')], max_length=20)),
                ('default_boolean_value', models.BooleanField(default=False)),
                ('default_numeric_value', models.PositiveIntegerField(default=0)),
                ('default_text_value', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'subscription_features',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField()),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'subscription_invoices',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Professional'), ('enterprise', 'Enterprise'), ('custom', 'Custom')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('quarterly', 'Quarterly'), ('one_time', 'One Time')], max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('max_users', models.PositiveIntegerField(default=1, help_text='Maximum users allowed')),
                ('max_organizations', models.PositiveIntegerField(default=1, help_text='Maximum organizations allowed')),
                ('max_api_calls_per_month', models.PositiveIntegerField(default=1000, help_text='API calls per month')),
                ('max_api_keys', models.PositiveIntegerField(default=1, help_text='Maximum API keys')),
                ('max_storage_gb', models.PositiveIntegerField(default=1, help_text='Storage limit in GB')),
                ('custom_branding', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('advanced_analytics', models.BooleanField(default=False)),
                ('sso_integration', models.BooleanField(default=False)),
                ('api_rate_limit_boost', models.BooleanField(default=False)),
                ('white_label', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True, help_text='Visible in public pricing')),
                ('trial_days', models.PositiveIntegerField(default=0, help_text='Free trial period in days')),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_type', models.CharField(choices=[('api_call', 'API Call'), ('storage', 'Storage'), ('user_addition', 'User Addition'), ('api_key_creation', 'API Key Creation'), ('organization_creation', 'Organization Creation')], max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('usage_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'usage_records',
                'ordering': ['-usage_date'],
            },
        ),
    ]
